/*
 * Copyright (C) 2019 EFA
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package gui.panels;

import db.DbConnection;
import gui.Main;

/**
 *
 * @author EFA
 */
public class TargetDetailsPanel extends javax.swing.JPanel {
    private final DbConnection mydb = new DbConnection();
    private final Main master;
    
    /**
     * Creates new form TargetDetailsPanel
     */
    public TargetDetailsPanel(Main master) {
        initComponents();
        this.master = master;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subpanel_photo = new org.jdesktop.swingx.JXPanel();
        lbl_photo = new javax.swing.JLabel();
        lbl_target_details_name = new javax.swing.JLabel();
        subpanel_graph_sky2 = new org.jdesktop.swingx.JXPanel();
        jLabel19 = new javax.swing.JLabel();
        slider_sky_graph2 = new javax.swing.JSlider();
        tabp_details = new javax.swing.JTabbedPane();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Tree.foreground"));
        setPreferredSize(new java.awt.Dimension(350, 663));

        subpanel_photo.setBackground(new java.awt.Color(0, 0, 0));
        subpanel_photo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        subpanel_photo.setPreferredSize(new java.awt.Dimension(334, 100));

        lbl_photo.setBackground(new java.awt.Color(0, 0, 0));
        lbl_photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_photo.setText("[No picture available.]");

        javax.swing.GroupLayout subpanel_photoLayout = new javax.swing.GroupLayout(subpanel_photo);
        subpanel_photo.setLayout(subpanel_photoLayout);
        subpanel_photoLayout.setHorizontalGroup(
            subpanel_photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanel_photoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        subpanel_photoLayout.setVerticalGroup(
            subpanel_photoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanel_photoLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(lbl_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addGap(102, 102, 102))
        );

        lbl_target_details_name.setBackground(javax.swing.UIManager.getDefaults().getColor("Nb.browser.picker.background.light"));
        lbl_target_details_name.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lbl_target_details_name.setForeground(new java.awt.Color(51, 51, 51));
        lbl_target_details_name.setText("Target details");

        subpanel_graph_sky2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        subpanel_graph_sky2.setPreferredSize(new java.awt.Dimension(334, 153));

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel19.setText("Graph");

        slider_sky_graph2.setMajorTickSpacing(10);
        slider_sky_graph2.setMaximum(23);
        slider_sky_graph2.setMinimum(-27);
        slider_sky_graph2.setMinorTickSpacing(2);
        slider_sky_graph2.setPaintTicks(true);
        slider_sky_graph2.setToolTipText("The apparent magnitude of the faintest object that is visible with the naked-eye or a telescope.");
        slider_sky_graph2.setValue(15);
        slider_sky_graph2.setName("slider_sky_graph"); // NOI18N
        slider_sky_graph2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_sky_graph2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout subpanel_graph_sky2Layout = new javax.swing.GroupLayout(subpanel_graph_sky2);
        subpanel_graph_sky2.setLayout(subpanel_graph_sky2Layout);
        subpanel_graph_sky2Layout.setHorizontalGroup(
            subpanel_graph_sky2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanel_graph_sky2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(subpanel_graph_sky2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(slider_sky_graph2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addGroup(subpanel_graph_sky2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        subpanel_graph_sky2Layout.setVerticalGroup(
            subpanel_graph_sky2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subpanel_graph_sky2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(slider_sky_graph2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_target_details_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subpanel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(subpanel_graph_sky2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(tabp_details))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_target_details_name, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(subpanel_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(tabp_details, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(subpanel_graph_sky2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slider_sky_graph2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_sky_graph2StateChanged
        
    }//GEN-LAST:event_slider_sky_graph2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel lbl_photo;
    private javax.swing.JLabel lbl_target_details_name;
    private javax.swing.JSlider slider_sky_graph;
    private javax.swing.JSlider slider_sky_graph1;
    private javax.swing.JSlider slider_sky_graph2;
    private org.jdesktop.swingx.JXPanel subpanel_graph_sky;
    private org.jdesktop.swingx.JXPanel subpanel_graph_sky1;
    private org.jdesktop.swingx.JXPanel subpanel_graph_sky2;
    private org.jdesktop.swingx.JXPanel subpanel_photo;
    private javax.swing.JTabbedPane tabp_details;
    // End of variables declaration//GEN-END:variables
}
